sudo: false
language: python
python: "3.5"
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=codestyle
  - TOXENV=pypi-lint

install: pip install tox
before_script: cp tests/config-travisci.py config.py
script: tox

# notification for gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/788e94bb42a75aa2df4c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
