language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

before_script:
  - cp tests/config-travisci.py config.py

install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install slackclient  # Optional dependency but Slack tests are skipped without it
  - pip freeze

script: ./run_tests.py


# New travis docker base build.
sudo: false

# notification for gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/788e94bb42a75aa2df4c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false
