language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

before_script:
  - cp errbot/config-travisci.py config.py

install:
  - python setup.py install
  - pip install --requirement requirements-development.txt PyOpenSSL
  - pip freeze

script: python run_tests.py

after_script:
  - pep8 --statistics --show-source
